esphome:
  name: fancontrol
  platform: ESP8266
  board: nodemcuv2
  includes: 
    - custom_sensor.h
  libraries: 
    - https://github.com/CoMPaTech/esphome_itho.git

wifi:
  ssid: !secret wifi_ssid 
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: 'fan'

ota:
  password: 'fan'

sensor:
- platform: custom
  lambda: |-
    auto my_sensor = new CC1101Component();
    App.register_component(my_sensor);
    return {my_sensor};

  sensors:
    name: "My Custom Sensor"
