esphome:
  name: smarthome
  platform: ESP8266
  board: nodemcuv2
  includes:
     - radio_frequ.h

wifi:
  ssid: "ENTER WIFI SSID"
  password: "ENTER PASSWORD"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
- platform: custom
  lambda: |-
    auto my_sensor = new MyCustomSensor();
    App.register_component(my_sensor);
    return {my_sensor};

  sensors:
    name: "radio sensor"
