esphome:
  on_boot:
    - lambda: 'ESP.eraseConfig();'
  name: smarthome
  platform: ESP8266
  board: nodemcuv2
  includes:
    - cc1101_component.h
    - libraries/radio/radio.h
    - libraries/radio/radio.cpp

wifi:
  ssid: !secret wifi_ssid 
  password: !secret wifi_password
  fast_connect: True

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

mqtt:
  broker: 192.168.0.73
  # username:       for remote mqtt broker
  # password:       for remote mqtt broker

custom_component:
  - lambda: |-
      auto my_custom = new CC1101Component();
      return {my_custom};
